"""Bounded async load test against a locally running instance (LLM_PROVIDER=mock).

Starts uvicorn itself, runs ~60s of concurrent /query traffic via httpx, records
real latencies, and writes evaluation/load_test_report.md, then stops the server.
"""
import asyncio
import statistics
import subprocess
import sys
import time
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[1]
BASE_URL = "http://127.0.0.1:8091"
DURATION_SECONDS = 60
CONCURRENCY = 15

QUESTIONS = [
    "What is the refund window for Starter plan customers?",
    "What encryption standard does Nimbus use at rest?",
    "How many requests per minute can a Team tier API key make?",
    "What support channels are available to Business tier customers?",
    "How long are deleted files kept before permanent deletion?",
]


async def worker(client: httpx.AsyncClient, worker_id: int, stop_at: float, latencies: list, status_codes: list) -> None:
    i = 0
    while time.monotonic() < stop_at:
        question = QUESTIONS[i % len(QUESTIONS)]
        # A distinct session_id per request simulates many different users, rather than
        # hammering the per-session rate limiter (a real security feature, not a bug).
        session_id = f"loadtest-{worker_id}-{i}"
        i += 1
        start = time.perf_counter()
        try:
            resp = await client.post("/query", json={"query": question, "session_id": session_id}, timeout=10.0)
            latencies.append((time.perf_counter() - start) * 1000)
            status_codes.append(resp.status_code)
        except Exception:
            status_codes.append("connection_error")


def percentile(values: list[float], pct: float) -> float:
    if not values:
        return 0.0
    values = sorted(values)
    idx = min(len(values) - 1, int(len(values) * pct))
    return values[idx]


async def main() -> None:
    proc = subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", "8091"],
        cwd=str(ROOT),
    )
    try:
        async with httpx.AsyncClient(base_url=BASE_URL) as client:
            for _ in range(60):
                try:
                    r = await client.get("/health", timeout=2.0)
                    if r.status_code == 200:
                        break
                except Exception:
                    pass
                await asyncio.sleep(1.0)
            else:
                raise RuntimeError("server did not become healthy in time")

            latencies: list[float] = []
            status_codes: list = []
            stop_at = time.monotonic() + DURATION_SECONDS
            start_wall = time.perf_counter()
            await asyncio.gather(
                *[worker(client, i, stop_at, latencies, status_codes) for i in range(CONCURRENCY)]
            )
            wall_seconds = time.perf_counter() - start_wall
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()

    total = len(status_codes)
    n_200 = sum(1 for c in status_codes if c == 200)
    n_429 = sum(1 for c in status_codes if c == 429)
    n_other_error = total - n_200 - n_429
    error_rate = n_other_error / total if total else 0.0
    report = f"""# Load Test Report

Generated by `scripts/load_test.py` against a locally running instance (LLM_PROVIDER=mock).

- Duration: {DURATION_SECONDS}s (wall clock: {wall_seconds:.1f}s)
- Concurrency: {CONCURRENCY} async workers, each using a unique session_id per request
- Total requests: {total}
- 200 OK: {n_200}
- 429 rate-limited (expected security behavior, not a failure): {n_429}
- Other errors: {n_other_error}
- Error rate (excluding intentional 429s): {error_rate:.2%}
- Throughput: {total / wall_seconds:.2f} req/s ({n_200 / wall_seconds:.2f} req/s served 200 OK)

## Latency (ms, successful requests only)

- p50: {percentile(latencies, 0.50):.1f}
- p95: {percentile(latencies, 0.95):.1f}
- p99: {percentile(latencies, 0.99):.1f}
- min: {min(latencies) if latencies else 0:.1f}
- max: {max(latencies) if latencies else 0:.1f}
- mean: {statistics.mean(latencies) if latencies else 0:.1f}
"""
    out_path = ROOT / "evaluation" / "load_test_report.md"
    out_path.write_text(report, encoding="utf-8")
    print(report)


if __name__ == "__main__":
    asyncio.run(main())
